import { createContext, useContext, useMemo, useReducer } from "react";

export interface Employee {
  area: string;
  facility: string;
  staffRoles: string;
  name: string;
  employeeId: string;
  // Level 1 Fields
  level1ReliasAssigned: Date | null;
  level1ReliasCompleted: Date | null;
  level1ConferenceCompleted: Date | null;
  level1Notes: string;
  level1Advisor: string;
  level1Awarded: boolean;
  level1AwardedDate: Date | null;
  level1AwaitingRelias: Date | null;
  // Level 2 Fields
  level2ReliasAssigned: Date | null;
  level2ReliasCompleted: Date | null;
  level2ConferenceCompleted: Date | null;
  level2Notes: string;
  level2Advisor: string;
  level2StandingVideo: Date | null;
  level2SleepingSittingVideo: Date | null;
  level2FeedingVideo: Date | null;
  level2Awarded: boolean;
  level2AwardedDate: Date | null;
  level2AwaitingRelias: Date | null;
  // Level 3 Fields
  level3ReliasAssigned: Date | null;
  level3ReliasCompleted: Date | null;
  level3ConferenceCompleted: Date | null;
  level3Notes: string;
  level3Advisor: string;
  level3SittingStandingApproaching: Date | null;
  level3NoHandNoSpeak: Date | null;
  level3ChallengeSleeping: Date | null;
  level3Awarded: boolean;
  level3AwardedDate: Date | null;
  level3AwaitingRelias: Date | null;
  // Consultant Fields
  consultantReliasAssigned: Date | null;
  consultantReliasCompleted: Date | null;
  consultantConferenceCompleted: Date | null;
  consultantNotes: string;
  consultantAdvisor: string;
  consultantCoachingSession1: Date | null;
  consultantCoachingSession2: Date | null;
  consultantCoachingSession3: Date | null;
  consultantAwarded: boolean;
  consultantAwardedDate: Date | null;
  consultantAwaitingRelias: Date | null;
  // Coach Fields
  coachReliasAssigned: Date | null;
  coachReliasCompleted: Date | null;
  coachConferenceCompleted: Date | null;
  coachNotes: string;
  coachAdvisor: string;
  coachCoachingSession1: Date | null;
  coachCoachingSession2: Date | null;
  coachCoachingSession3: Date | null;
  coachAwarded: boolean;
  coachAwardedDate: Date | null;
  coachAwaitingRelias: Date | null;
}

export interface DashboardStats {
  totalEmployees: number;
  completionRates: {
    carePartner: number;
    associate: number;
    champion: number;
    consultant: number;
    coach: number;
  };
  pendingAssignments: number;
  overdueTraining: number;
  facilitiesCount: number;
  areasCount: number;
}

interface FilterState {
  query: string;
  facility?: string;
  area?: string;
}

interface AppState {
  employees: Employee[];
  filters: FilterState;
  selectedEmployee: Employee | null;
}

type Action =
  | { type: "setEmployees"; payload: Employee[] }
  | { type: "setQuery"; payload: string }
  | { type: "selectEmployee"; payload: Employee | null };

const AppContext = createContext<{
  state: AppState;
  dispatch: React.Dispatch<Action>;
}>({ state: { employees: [], filters: { query: "" }, selectedEmployee: null }, dispatch: () => {} });

function reducer(state: AppState, action: Action): AppState {
  switch (action.type) {
    case "setEmployees":
      return { ...state, employees: action.payload };
    case "setQuery":
      return { ...state, filters: { ...state.filters, query: action.payload } };
    case "selectEmployee":
      return { ...state, selectedEmployee: action.payload };
    default:
      return state;
  }
}

const mockEmployees: Employee[] = [
  {
    area: "North",
    facility: "Evergreen",
    staffRoles: "Caregiver",
    name: "Alex Johnson",
    employeeId: "E-1001",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-02-01"),
    level1ReliasCompleted: new Date("2024-02-20"),
    level1ConferenceCompleted: new Date("2024-02-22"),
    level1Notes: "Completed Level 1 training successfully",
    level1Advisor: "Dr. Smith",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-02-25"),
    level1AwaitingRelias: null,
    // Level 2 - IN PROGRESS
    level2ReliasAssigned: new Date("2024-03-01"),
    level2ReliasCompleted: new Date("2024-03-15"),
    level2ConferenceCompleted: new Date("2024-03-20"),
    level2Notes: "Working on video submissions",
    level2Advisor: "Dr. Smith",
    level2StandingVideo: new Date("2024-03-25"),
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "South",
    facility: "Lakeside",
    staffRoles: "Nurse",
    name: "Maria Chen",
    employeeId: "E-1002",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-05"),
    level1ReliasCompleted: new Date("2024-01-20"),
    level1ConferenceCompleted: new Date("2024-01-22"),
    level1Notes: "Excellent Level 1 completion",
    level1Advisor: "Dr. Lee",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-01-25"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-02-01"),
    level2ReliasCompleted: new Date("2024-02-25"),
    level2ConferenceCompleted: new Date("2024-03-05"),
    level2Notes: "Great progress on Level 2",
    level2Advisor: "Dr. Lee",
    level2StandingVideo: new Date("2024-03-10"),
    level2SleepingSittingVideo: new Date("2024-03-15"),
    level2FeedingVideo: new Date("2024-03-18"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-03-20"),
    level2AwaitingRelias: null,
    // Level 3 - IN PROGRESS
    level3ReliasAssigned: new Date("2024-04-01"),
    level3ReliasCompleted: new Date("2024-04-15"),
    level3ConferenceCompleted: new Date("2024-04-20"),
    level3Notes: "Working on advanced techniques",
    level3Advisor: "Dr. Brown",
    level3SittingStandingApproaching: new Date("2024-04-25"),
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "East",
    facility: "Hilltop",
    staffRoles: "Therapist",
    name: "Sarah Williams",
    employeeId: "E-1003",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-15"),
    level1ReliasCompleted: new Date("2024-02-05"),
    level1ConferenceCompleted: new Date("2024-02-07"),
    level1Notes: "Strong Level 1 foundation",
    level1Advisor: "Dr. Johnson",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-02-10"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-03-15"),
    level2ReliasCompleted: new Date("2024-04-10"),
    level2ConferenceCompleted: new Date("2024-04-20"),
    level2Notes: "Excellent video submissions",
    level2Advisor: "Dr. Johnson",
    level2StandingVideo: new Date("2024-04-25"),
    level2SleepingSittingVideo: new Date("2024-04-28"),
    level2FeedingVideo: new Date("2024-05-02"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-05-05"),
    level2AwaitingRelias: null,
    // Level 3 - COMPLETED
    level3ReliasAssigned: new Date("2024-05-15"),
    level3ReliasCompleted: new Date("2024-06-01"),
    level3ConferenceCompleted: new Date("2024-06-15"),
    level3Notes: "Advanced techniques mastered",
    level3Advisor: "Dr. Brown",
    level3SittingStandingApproaching: new Date("2024-06-20"),
    level3NoHandNoSpeak: new Date("2024-06-25"),
    level3ChallengeSleeping: new Date("2024-06-30"),
    level3Awarded: true,
    level3AwardedDate: new Date("2024-07-05"),
    level3AwaitingRelias: null,
    // Consultant - IN PROGRESS
    consultantReliasAssigned: new Date("2024-07-01"),
    consultantReliasCompleted: new Date("2024-07-15"),
    consultantConferenceCompleted: new Date("2024-07-20"),
    consultantNotes: "Starting consultant training",
    consultantAdvisor: "Dr. Wilson",
    consultantCoachingSession1: new Date("2024-07-25"),
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "West",
    facility: "Sunset",
    staffRoles: "Manager",
    name: "Michael Rodriguez",
    employeeId: "E-1004",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-10"),
    level1ReliasCompleted: new Date("2024-01-25"),
    level1ConferenceCompleted: new Date("2024-01-27"),
    level1Notes: "Strong Level 1 completion",
    level1Advisor: "Dr. Davis",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-01-30"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-02-15"),
    level2ReliasCompleted: new Date("2024-03-10"),
    level2ConferenceCompleted: new Date("2024-03-20"),
    level2Notes: "Strong leadership skills",
    level2Advisor: "Dr. Davis",
    level2StandingVideo: new Date("2024-03-25"),
    level2SleepingSittingVideo: new Date("2024-03-28"),
    level2FeedingVideo: new Date("2024-04-02"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-04-05"),
    level2AwaitingRelias: null,
    // Level 3 - COMPLETED
    level3ReliasAssigned: new Date("2024-04-15"),
    level3ReliasCompleted: new Date("2024-05-10"),
    level3ConferenceCompleted: new Date("2024-05-25"),
    level3Notes: "Excellent coaching abilities",
    level3Advisor: "Dr. Martinez",
    level3SittingStandingApproaching: new Date("2024-06-01"),
    level3NoHandNoSpeak: new Date("2024-06-05"),
    level3ChallengeSleeping: new Date("2024-06-10"),
    level3Awarded: true,
    level3AwardedDate: new Date("2024-06-15"),
    level3AwaitingRelias: null,
    // Consultant - COMPLETED
    consultantReliasAssigned: new Date("2024-06-15"),
    consultantReliasCompleted: new Date("2024-07-01"),
    consultantConferenceCompleted: new Date("2024-07-15"),
    consultantNotes: "Ready for coaching sessions",
    consultantAdvisor: "Dr. Thompson",
    consultantCoachingSession1: new Date("2024-07-20"),
    consultantCoachingSession2: new Date("2024-08-01"),
    consultantCoachingSession3: new Date("2024-08-15"),
    consultantAwarded: true,
    consultantAwardedDate: new Date("2024-08-20"),
    consultantAwaitingRelias: null,
    // Coach - IN PROGRESS
    coachReliasAssigned: new Date("2024-08-20"),
    coachReliasCompleted: new Date("2024-09-01"),
    coachConferenceCompleted: new Date("2024-09-15"),
    coachNotes: "Starting coach level",
    coachAdvisor: "Dr. Anderson",
    coachCoachingSession1: new Date("2024-09-20"),
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "Central",
    facility: "Evergreen",
    staffRoles: "Caregiver",
    name: "Jennifer Lee",
    employeeId: "E-1005",
    // Level 1 - IN PROGRESS
    level1ReliasAssigned: new Date("2024-02-15"),
    level1ReliasCompleted: new Date("2024-03-01"),
    level1ConferenceCompleted: null,
    level1Notes: "Working on conference completion",
    level1Advisor: "Dr. Wilson",
    level1Awarded: false,
    level1AwardedDate: null,
    level1AwaitingRelias: null,
    // Level 2 - NOT STARTED
    level2ReliasAssigned: null,
    level2ReliasCompleted: null,
    level2ConferenceCompleted: null,
    level2Notes: "",
    level2Advisor: "",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "North",
    facility: "Evergreen",
    staffRoles: "Nurse",
    name: "David Thompson",
    employeeId: "E-1006",
    // Level 1 - NOT STARTED
    level1ReliasAssigned: null,
    level1ReliasCompleted: null,
    level1ConferenceCompleted: null,
    level1Notes: "",
    level1Advisor: "",
    level1Awarded: false,
    level1AwardedDate: null,
    level1AwaitingRelias: null,
    // Level 2 - NOT STARTED
    level2ReliasAssigned: null,
    level2ReliasCompleted: null,
    level2ConferenceCompleted: null,
    level2Notes: "",
    level2Advisor: "",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "South",
    facility: "Lakeside",
    staffRoles: "Therapist",
    name: "Emily Davis",
    employeeId: "E-1007",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-20"),
    level1ReliasCompleted: new Date("2024-02-10"),
    level1ConferenceCompleted: new Date("2024-02-12"),
    level1Notes: "Excellent Level 1 performance",
    level1Advisor: "Dr. Wilson",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-02-15"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-03-01"),
    level2ReliasCompleted: new Date("2024-03-20"),
    level2ConferenceCompleted: new Date("2024-03-25"),
    level2Notes: "Strong Level 2 completion",
    level2Advisor: "Dr. Wilson",
    level2StandingVideo: new Date("2024-03-30"),
    level2SleepingSittingVideo: new Date("2024-04-05"),
    level2FeedingVideo: new Date("2024-04-10"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-04-15"),
    level2AwaitingRelias: null,
    // Level 3 - COMPLETED
    level3ReliasAssigned: new Date("2024-04-20"),
    level3ReliasCompleted: new Date("2024-05-15"),
    level3ConferenceCompleted: new Date("2024-05-25"),
    level3Notes: "Advanced skills mastered",
    level3Advisor: "Dr. Brown",
    level3SittingStandingApproaching: new Date("2024-06-01"),
    level3NoHandNoSpeak: new Date("2024-06-05"),
    level3ChallengeSleeping: new Date("2024-06-10"),
    level3Awarded: true,
    level3AwardedDate: new Date("2024-06-15"),
    level3AwaitingRelias: null,
    // Consultant - COMPLETED
    consultantReliasAssigned: new Date("2024-06-20"),
    consultantReliasCompleted: new Date("2024-07-10"),
    consultantConferenceCompleted: new Date("2024-07-20"),
    consultantNotes: "Ready for coaching",
    consultantAdvisor: "Dr. Thompson",
    consultantCoachingSession1: new Date("2024-07-25"),
    consultantCoachingSession2: new Date("2024-08-05"),
    consultantCoachingSession3: new Date("2024-08-15"),
    consultantAwarded: true,
    consultantAwardedDate: new Date("2024-08-20"),
    consultantAwaitingRelias: null,
    // Coach - COMPLETED
    coachReliasAssigned: new Date("2024-08-25"),
    coachReliasCompleted: new Date("2024-09-10"),
    coachConferenceCompleted: new Date("2024-09-20"),
    coachNotes: "Coach level achieved",
    coachAdvisor: "Dr. Anderson",
    coachCoachingSession1: new Date("2024-09-25"),
    coachCoachingSession2: new Date("2024-10-05"),
    coachCoachingSession3: new Date("2024-10-15"),
    coachAwarded: true,
    coachAwardedDate: new Date("2024-10-20"),
    coachAwaitingRelias: null,
  },
  {
    area: "East",
    facility: "Hilltop",
    staffRoles: "Caregiver",
    name: "Robert Wilson",
    employeeId: "E-1008",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-02-01"),
    level1ReliasCompleted: new Date("2024-02-20"),
    level1ConferenceCompleted: new Date("2024-02-22"),
    level1Notes: "Good Level 1 foundation",
    level1Advisor: "Dr. Smith",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-02-25"),
    level1AwaitingRelias: null,
    // Level 2 - IN PROGRESS
    level2ReliasAssigned: new Date("2024-03-01"),
    level2ReliasCompleted: new Date("2024-03-15"),
    level2ConferenceCompleted: null,
    level2Notes: "Working on conference completion",
    level2Advisor: "Dr. Smith",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "West",
    facility: "Sunset",
    staffRoles: "Nurse",
    name: "Lisa Anderson",
    employeeId: "E-1009",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-15"),
    level1ReliasCompleted: new Date("2024-02-05"),
    level1ConferenceCompleted: new Date("2024-02-07"),
    level1Notes: "Strong Level 1 completion",
    level1Advisor: "Dr. Lee",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-02-10"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-03-01"),
    level2ReliasCompleted: new Date("2024-03-20"),
    level2ConferenceCompleted: new Date("2024-03-25"),
    level2Notes: "Excellent video submissions",
    level2Advisor: "Dr. Lee",
    level2StandingVideo: new Date("2024-03-30"),
    level2SleepingSittingVideo: new Date("2024-04-05"),
    level2FeedingVideo: new Date("2024-04-10"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-04-15"),
    level2AwaitingRelias: null,
    // Level 3 - IN PROGRESS
    level3ReliasAssigned: new Date("2024-04-20"),
    level3ReliasCompleted: new Date("2024-05-10"),
    level3ConferenceCompleted: null,
    level3Notes: "Working on advanced techniques",
    level3Advisor: "Dr. Brown",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "Central",
    facility: "Evergreen",
    staffRoles: "Therapist",
    name: "James Martinez",
    employeeId: "E-1010",
    // Level 1 - IN PROGRESS
    level1ReliasAssigned: new Date("2024-03-01"),
    level1ReliasCompleted: null,
    level1ConferenceCompleted: null,
    level1Notes: "Started Level 1 training",
    level1Advisor: "Dr. Johnson",
    level1Awarded: false,
    level1AwardedDate: null,
    level1AwaitingRelias: null,
    // Level 2 - NOT STARTED
    level2ReliasAssigned: null,
    level2ReliasCompleted: null,
    level2ConferenceCompleted: null,
    level2Notes: "",
    level2Advisor: "",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "North",
    facility: "Evergreen",
    staffRoles: "Manager",
    name: "Patricia Garcia",
    employeeId: "E-1011",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-10"),
    level1ReliasCompleted: new Date("2024-01-25"),
    level1ConferenceCompleted: new Date("2024-01-27"),
    level1Notes: "Strong leadership foundation",
    level1Advisor: "Dr. Davis",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-01-30"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-02-15"),
    level2ReliasCompleted: new Date("2024-03-10"),
    level2ConferenceCompleted: new Date("2024-03-20"),
    level2Notes: "Excellent management skills",
    level2Advisor: "Dr. Davis",
    level2StandingVideo: new Date("2024-03-25"),
    level2SleepingSittingVideo: new Date("2024-03-28"),
    level2FeedingVideo: new Date("2024-04-02"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-04-05"),
    level2AwaitingRelias: null,
    // Level 3 - COMPLETED
    level3ReliasAssigned: new Date("2024-04-15"),
    level3ReliasCompleted: new Date("2024-05-10"),
    level3ConferenceCompleted: new Date("2024-05-25"),
    level3Notes: "Advanced leadership achieved",
    level3Advisor: "Dr. Martinez",
    level3SittingStandingApproaching: new Date("2024-06-01"),
    level3NoHandNoSpeak: new Date("2024-06-05"),
    level3ChallengeSleeping: new Date("2024-06-10"),
    level3Awarded: true,
    level3AwardedDate: new Date("2024-06-15"),
    level3AwaitingRelias: null,
    // Consultant - COMPLETED
    consultantReliasAssigned: new Date("2024-06-20"),
    consultantReliasCompleted: new Date("2024-07-10"),
    consultantConferenceCompleted: new Date("2024-07-20"),
    consultantNotes: "Ready for coaching role",
    consultantAdvisor: "Dr. Thompson",
    consultantCoachingSession1: new Date("2024-07-25"),
    consultantCoachingSession2: new Date("2024-08-05"),
    consultantCoachingSession3: new Date("2024-08-15"),
    consultantAwarded: true,
    consultantAwardedDate: new Date("2024-08-20"),
    consultantAwaitingRelias: null,
    // Coach - IN PROGRESS
    coachReliasAssigned: new Date("2024-08-25"),
    coachReliasCompleted: new Date("2024-09-10"),
    coachConferenceCompleted: null,
    coachNotes: "Working on coach certification",
    coachAdvisor: "Dr. Anderson",
    coachCoachingSession1: new Date("2024-09-15"),
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "South",
    facility: "Lakeside",
    staffRoles: "Caregiver",
    name: "Thomas Brown",
    employeeId: "E-1012",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-02-01"),
    level1ReliasCompleted: new Date("2024-02-20"),
    level1ConferenceCompleted: new Date("2024-02-22"),
    level1Notes: "Good Level 1 completion",
    level1Advisor: "Dr. Smith",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-02-25"),
    level1AwaitingRelias: null,
    // Level 2 - IN PROGRESS
    level2ReliasAssigned: new Date("2024-03-01"),
    level2ReliasCompleted: new Date("2024-03-15"),
    level2ConferenceCompleted: new Date("2024-03-20"),
    level2Notes: "Working on video submissions",
    level2Advisor: "Dr. Smith",
    level2StandingVideo: new Date("2024-03-25"),
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "East",
    facility: "Hilltop",
    staffRoles: "Nurse",
    name: "Amanda Taylor",
    employeeId: "E-1013",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-15"),
    level1ReliasCompleted: new Date("2024-02-05"),
    level1ConferenceCompleted: new Date("2024-02-07"),
    level1Notes: "Excellent Level 1 foundation",
    level1Advisor: "Dr. Johnson",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-02-10"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-03-01"),
    level2ReliasCompleted: new Date("2024-03-20"),
    level2ConferenceCompleted: new Date("2024-03-25"),
    level2Notes: "Strong Level 2 completion",
    level2Advisor: "Dr. Johnson",
    level2StandingVideo: new Date("2024-03-30"),
    level2SleepingSittingVideo: new Date("2024-04-05"),
    level2FeedingVideo: new Date("2024-04-10"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-04-15"),
    level2AwaitingRelias: null,
    // Level 3 - IN PROGRESS
    level3ReliasAssigned: new Date("2024-04-20"),
    level3ReliasCompleted: new Date("2024-05-10"),
    level3ConferenceCompleted: null,
    level3Notes: "Working on advanced techniques",
    level3Advisor: "Dr. Brown",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "West",
    facility: "Sunset",
    staffRoles: "Therapist",
    name: "Christopher Lee",
    employeeId: "E-1014",
    // Level 1 - IN PROGRESS
    level1ReliasAssigned: new Date("2024-03-15"),
    level1ReliasCompleted: new Date("2024-04-01"),
    level1ConferenceCompleted: null,
    level1Notes: "Working on conference completion",
    level1Advisor: "Dr. Wilson",
    level1Awarded: false,
    level1AwardedDate: null,
    level1AwaitingRelias: null,
    // Level 2 - NOT STARTED
    level2ReliasAssigned: null,
    level2ReliasCompleted: null,
    level2ConferenceCompleted: null,
    level2Notes: "",
    level2Advisor: "",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "Central",
    facility: "Evergreen",
    staffRoles: "Nurse",
    name: "Jessica White",
    employeeId: "E-1015",
    // Level 1 - NOT STARTED
    level1ReliasAssigned: null,
    level1ReliasCompleted: null,
    level1ConferenceCompleted: null,
    level1Notes: "",
    level1Advisor: "",
    level1Awarded: false,
    level1AwardedDate: null,
    level1AwaitingRelias: null,
    // Level 2 - NOT STARTED
    level2ReliasAssigned: null,
    level2ReliasCompleted: null,
    level2ConferenceCompleted: null,
    level2Notes: "",
    level2Advisor: "",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "North",
    facility: "Evergreen",
    staffRoles: "Caregiver",
    name: "Daniel Clark",
    employeeId: "E-1016",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-02-10"),
    level1ReliasCompleted: new Date("2024-02-25"),
    level1ConferenceCompleted: new Date("2024-02-27"),
    level1Notes: "Good Level 1 completion",
    level1Advisor: "Dr. Smith",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-03-01"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-03-10"),
    level2ReliasCompleted: new Date("2024-03-25"),
    level2ConferenceCompleted: new Date("2024-04-05"),
    level2Notes: "Strong Level 2 completion",
    level2Advisor: "Dr. Smith",
    level2StandingVideo: new Date("2024-04-10"),
    level2SleepingSittingVideo: new Date("2024-04-15"),
    level2FeedingVideo: new Date("2024-04-20"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-04-25"),
    level2AwaitingRelias: null,
    // Level 3 - COMPLETED
    level3ReliasAssigned: new Date("2024-05-01"),
    level3ReliasCompleted: new Date("2024-05-20"),
    level3ConferenceCompleted: new Date("2024-06-01"),
    level3Notes: "Advanced skills achieved",
    level3Advisor: "Dr. Brown",
    level3SittingStandingApproaching: new Date("2024-06-05"),
    level3NoHandNoSpeak: new Date("2024-06-10"),
    level3ChallengeSleeping: new Date("2024-06-15"),
    level3Awarded: true,
    level3AwardedDate: new Date("2024-06-20"),
    level3AwaitingRelias: null,
    // Consultant - IN PROGRESS
    consultantReliasAssigned: new Date("2024-06-25"),
    consultantReliasCompleted: new Date("2024-07-15"),
    consultantConferenceCompleted: null,
    consultantNotes: "Working on consultant level",
    consultantAdvisor: "Dr. Thompson",
    consultantCoachingSession1: new Date("2024-07-20"),
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "South",
    facility: "Lakeside",
    staffRoles: "Therapist",
    name: "Rachel Green",
    employeeId: "E-1017",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-25"),
    level1ReliasCompleted: new Date("2024-02-15"),
    level1ConferenceCompleted: new Date("2024-02-17"),
    level1Notes: "Excellent Level 1 foundation",
    level1Advisor: "Dr. Wilson",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-02-20"),
    level1AwaitingRelias: null,
    // Level 2 - IN PROGRESS
    level2ReliasAssigned: new Date("2024-03-01"),
    level2ReliasCompleted: new Date("2024-03-20"),
    level2ConferenceCompleted: null,
    level2Notes: "Working on video submissions",
    level2Advisor: "Dr. Wilson",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "East",
    facility: "Hilltop",
    staffRoles: "Nurse",
    name: "Kevin Johnson",
    employeeId: "E-1018",
    // Level 1 - IN PROGRESS
    level1ReliasAssigned: new Date("2024-03-20"),
    level1ReliasCompleted: null,
    level1ConferenceCompleted: null,
    level1Notes: "Started Level 1 training",
    level1Advisor: "Dr. Johnson",
    level1Awarded: false,
    level1AwardedDate: null,
    level1AwaitingRelias: null,
    // Level 2 - NOT STARTED
    level2ReliasAssigned: null,
    level2ReliasCompleted: null,
    level2ConferenceCompleted: null,
    level2Notes: "",
    level2Advisor: "",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
  {
    area: "West",
    facility: "Sunset",
    staffRoles: "Manager",
    name: "Michelle Davis",
    employeeId: "E-1019",
    // Level 1 - COMPLETED
    level1ReliasAssigned: new Date("2024-01-05"),
    level1ReliasCompleted: new Date("2024-01-20"),
    level1ConferenceCompleted: new Date("2024-01-22"),
    level1Notes: "Strong Level 1 completion",
    level1Advisor: "Dr. Lee",
    level1Awarded: true,
    level1AwardedDate: new Date("2024-01-25"),
    level1AwaitingRelias: null,
    // Level 2 - COMPLETED
    level2ReliasAssigned: new Date("2024-02-01"),
    level2ReliasCompleted: new Date("2024-02-25"),
    level2ConferenceCompleted: new Date("2024-03-05"),
    level2Notes: "Excellent management skills",
    level2Advisor: "Dr. Lee",
    level2StandingVideo: new Date("2024-03-10"),
    level2SleepingSittingVideo: new Date("2024-03-15"),
    level2FeedingVideo: new Date("2024-03-18"),
    level2Awarded: true,
    level2AwardedDate: new Date("2024-03-20"),
    level2AwaitingRelias: null,
    // Level 3 - COMPLETED
    level3ReliasAssigned: new Date("2024-04-01"),
    level3ReliasCompleted: new Date("2024-04-25"),
    level3ConferenceCompleted: new Date("2024-05-10"),
    level3Notes: "Advanced leadership achieved",
    level3Advisor: "Dr. Brown",
    level3SittingStandingApproaching: new Date("2024-05-15"),
    level3NoHandNoSpeak: new Date("2024-05-20"),
    level3ChallengeSleeping: new Date("2024-05-25"),
    level3Awarded: true,
    level3AwardedDate: new Date("2024-05-30"),
    level3AwaitingRelias: null,
    // Consultant - COMPLETED
    consultantReliasAssigned: new Date("2024-06-01"),
    consultantReliasCompleted: new Date("2024-06-20"),
    consultantConferenceCompleted: new Date("2024-07-01"),
    consultantNotes: "Ready for coaching role",
    consultantAdvisor: "Dr. Thompson",
    consultantCoachingSession1: new Date("2024-07-05"),
    consultantCoachingSession2: new Date("2024-07-15"),
    consultantCoachingSession3: new Date("2024-07-25"),
    consultantAwarded: true,
    consultantAwardedDate: new Date("2024-07-30"),
    consultantAwaitingRelias: null,
    // Coach - COMPLETED
    coachReliasAssigned: new Date("2024-08-01"),
    coachReliasCompleted: new Date("2024-08-20"),
    coachConferenceCompleted: new Date("2024-09-01"),
    coachNotes: "Coach level achieved",
    coachAdvisor: "Dr. Anderson",
    coachCoachingSession1: new Date("2024-09-05"),
    coachCoachingSession2: new Date("2024-09-15"),
    coachCoachingSession3: new Date("2024-09-25"),
    coachAwarded: true,
    coachAwardedDate: new Date("2024-09-30"),
    coachAwaitingRelias: null,
  },
  {
    area: "Central",
    facility: "Evergreen",
    staffRoles: "Caregiver",
    name: "Steven Wilson",
    employeeId: "E-1020",
    // Level 1 - NOT STARTED
    level1ReliasAssigned: null,
    level1ReliasCompleted: null,
    level1ConferenceCompleted: null,
    level1Notes: "",
    level1Advisor: "",
    level1Awarded: false,
    level1AwardedDate: null,
    level1AwaitingRelias: null,
    // Level 2 - NOT STARTED
    level2ReliasAssigned: null,
    level2ReliasCompleted: null,
    level2ConferenceCompleted: null,
    level2Notes: "",
    level2Advisor: "",
    level2StandingVideo: null,
    level2SleepingSittingVideo: null,
    level2FeedingVideo: null,
    level2Awarded: false,
    level2AwardedDate: null,
    level2AwaitingRelias: null,
    // Level 3 - NOT STARTED
    level3ReliasAssigned: null,
    level3ReliasCompleted: null,
    level3ConferenceCompleted: null,
    level3Notes: "",
    level3Advisor: "",
    level3SittingStandingApproaching: null,
    level3NoHandNoSpeak: null,
    level3ChallengeSleeping: null,
    level3Awarded: false,
    level3AwardedDate: null,
    level3AwaitingRelias: null,
    // Consultant - NOT STARTED
    consultantReliasAssigned: null,
    consultantReliasCompleted: null,
    consultantConferenceCompleted: null,
    consultantNotes: "",
    consultantAdvisor: "",
    consultantCoachingSession1: null,
    consultantCoachingSession2: null,
    consultantCoachingSession3: null,
    consultantAwarded: false,
    consultantAwardedDate: null,
    consultantAwaitingRelias: null,
    // Coach - NOT STARTED
    coachReliasAssigned: null,
    coachReliasCompleted: null,
    coachConferenceCompleted: null,
    coachNotes: "",
    coachAdvisor: "",
    coachCoachingSession1: null,
    coachCoachingSession2: null,
    coachCoachingSession3: null,
    coachAwarded: false,
    coachAwardedDate: null,
    coachAwaitingRelias: null,
  },
];

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [state, dispatch] = useReducer(reducer, {
    employees: mockEmployees,
    filters: { query: "" },
    selectedEmployee: null,
  });

  const value = useMemo(() => ({ state, dispatch }), [state]);
  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be used within AppProvider");
  return ctx;
}
